import type { RequiredDataFromCollectionSlug } from 'payload'

type SponsorSeedData = Omit<RequiredDataFromCollectionSlug<'sponsors'>, 'logo'>

export const golfSponsors: SponsorSeedData[] = [
  {
    name: 'Bank Jatim',
    slug: 'bank-jatim',
    tier: 'title',
    order: 1,
    isActive: true,
    website: 'https://www.bankjatim.co.id',
    description: 'Regional development bank serving East Java with comprehensive financial services.',
    benefits: [
      { benefit: 'Title naming rights for Annual Championship' },
      { benefit: 'Exclusive branding on all event materials' },
      { benefit: 'VIP hospitality suite at all major events' },
      { benefit: 'Speaking opportunity at awards ceremony' },
      { benefit: 'Custom activation zone at tournaments' },
    ],
  },
  {
    name: 'Semen Indonesia',
    slug: 'semen-indonesia',
    tier: 'platinum',
    order: 1,
    isActive: true,
    website: 'https://www.semenindonesia.com',
    description: 'Leading cement and building materials company in Indonesia.',
    benefits: [
      { benefit: 'Premium logo placement on event materials' },
      { benefit: 'VIP access to all events' },
      { benefit: 'Social media feature campaigns' },
      { benefit: 'Banner placement at all tournaments' },
    ],
  },
  {
    name: 'Telkom Indonesia',
    slug: 'telkom-indonesia',
    tier: 'platinum',
    order: 2,
    isActive: true,
    website: 'https://www.telkom.co.id',
    description: 'Indonesia largest telecommunications and network provider.',
    benefits: [
      { benefit: 'Premium logo placement on event materials' },
      { benefit: 'VIP access to all events' },
      { benefit: 'Social media feature campaigns' },
      { benefit: 'Banner placement at all tournaments' },
    ],
  },
  {
    name: 'Gudang Garam',
    slug: 'gudang-garam',
    tier: 'gold',
    order: 1,
    isActive: true,
    website: 'https://www.gudanggaramtbk.com',
    description: 'One of the largest cigarette producers in Indonesia.',
    benefits: [
      { benefit: 'Logo on website sponsor page' },
      { benefit: 'Social media mentions' },
      { benefit: 'Event signage placement' },
    ],
  },
  {
    name: 'BCA',
    slug: 'bca',
    tier: 'gold',
    order: 2,
    isActive: true,
    website: 'https://www.bca.co.id',
    description: 'Indonesia leading private bank with nationwide coverage.',
    benefits: [
      { benefit: 'Logo on website sponsor page' },
      { benefit: 'Social media mentions' },
      { benefit: 'Event signage placement' },
    ],
  },
  {
    name: 'Petrokimia Gresik',
    slug: 'petrokimia-gresik',
    tier: 'gold',
    order: 3,
    isActive: true,
    website: 'https://www.petrokimia-gresik.com',
    description: 'Largest fertilizer producer in Indonesia.',
    benefits: [
      { benefit: 'Logo on website sponsor page' },
      { benefit: 'Social media mentions' },
      { benefit: 'Event signage placement' },
    ],
  },
  {
    name: 'Sinarmas',
    slug: 'sinarmas',
    tier: 'gold',
    order: 4,
    isActive: true,
    website: 'https://www.sinarmas.com',
    description: 'Diversified conglomerate with interests in pulp, paper, and financial services.',
    benefits: [
      { benefit: 'Logo on website sponsor page' },
      { benefit: 'Social media mentions' },
      { benefit: 'Event signage placement' },
    ],
  },
  {
    name: 'Astra International',
    slug: 'astra-international',
    tier: 'gold',
    order: 5,
    isActive: true,
    website: 'https://www.astra.co.id',
    description: 'Indonesia largest diversified conglomerate with automotive, financial, and infrastructure businesses.',
    benefits: [
      { benefit: 'Logo on website sponsor page' },
      { benefit: 'Social media mentions' },
      { benefit: 'Event signage placement' },
    ],
  },
  {
    name: 'Pertamina',
    slug: 'pertamina',
    tier: 'platinum',
    order: 3,
    isActive: true,
    website: 'https://www.pertamina.com',
    description: 'Indonesia state-owned oil and natural gas corporation.',
    benefits: [
      { benefit: 'Premium logo placement on event materials' },
      { benefit: 'VIP access to all events' },
      { benefit: 'Social media feature campaigns' },
      { benefit: 'Banner placement at all tournaments' },
    ],
  },
  {
    name: 'Indofood',
    slug: 'indofood',
    tier: 'gold',
    order: 6,
    isActive: true,
    website: 'https://www.indofood.com',
    description: 'Total food solutions company and one of the largest food companies in the world.',
    benefits: [
      { benefit: 'Logo on website sponsor page' },
      { benefit: 'Social media mentions' },
      { benefit: 'Event signage placement' },
    ],
  },
]
