import type { RequiredDataFromCollectionSlug } from 'payload'

type PlayerSeedData = Omit<RequiredDataFromCollectionSlug<'players'>, 'image'>

export const golfPlayers: PlayerSeedData[] = [
  {
    name: 'Ahmad Rizki Pratama',
    slug: 'ahmad-rizki-pratama',
    rank: 1,
    country: 'Indonesia',
    gender: 'male',
    status: 'active',
    wins: 12,
    points: 2450,
    handicap: 2,
    latestGrossScore: 68,
    majorChampionships: 3,
    age: 32,
    turnedPro: 2015,
    memberId: 'APGC-001',
    email: 'ahmad.rizki@apgc.com',
    matchPlayAvailable: true,
    isFeatured: true,
    memberDescription: 'Three-time APGC Champion with consistent top-10 finishes.',
    recentResults: [
      { tournament: 'APGC Spring Championship', position: '1st', date: '2024-03-15' },
      { tournament: 'Alumni Invitational', position: '2nd', date: '2024-02-20' },
      { tournament: 'Winter Classic', position: '1st', date: '2024-01-10' },
    ],
  },
  {
    name: 'Budi Santoso',
    slug: 'budi-santoso',
    rank: 2,
    country: 'Indonesia',
    gender: 'male',
    status: 'active',
    wins: 8,
    points: 2100,
    handicap: 3,
    latestGrossScore: 70,
    majorChampionships: 2,
    age: 28,
    turnedPro: 2018,
    memberId: 'APGC-002',
    email: 'budi.santoso@apgc.com',
    matchPlayAvailable: true,
    isFeatured: true,
    memberDescription: 'Rising star with exceptional short game skills.',
    recentResults: [
      { tournament: 'APGC Spring Championship', position: '3rd', date: '2024-03-15' },
      { tournament: 'Alumni Invitational', position: '1st', date: '2024-02-20' },
    ],
  },
  {
    name: 'Citra Dewi Lestari',
    slug: 'citra-dewi-lestari',
    rank: 3,
    country: 'Indonesia',
    gender: 'female',
    status: 'active',
    wins: 6,
    points: 1950,
    handicap: 4,
    latestGrossScore: 72,
    majorChampionships: 1,
    age: 26,
    turnedPro: 2019,
    memberId: 'APGC-003',
    email: 'citra.dewi@apgc.com',
    matchPlayAvailable: true,
    isFeatured: true,
    memberDescription: 'First female champion of the APGC Alumni Championship.',
    recentResults: [
      { tournament: 'APGC Spring Championship', position: '5th', date: '2024-03-15' },
      { tournament: "Women's Invitational", position: '1st', date: '2024-02-25' },
    ],
  },
  {
    name: 'Denny Wijaya',
    slug: 'denny-wijaya',
    rank: 4,
    country: 'Indonesia',
    gender: 'male',
    status: 'active',
    wins: 5,
    points: 1800,
    handicap: 5,
    latestGrossScore: 73,
    majorChampionships: 1,
    age: 35,
    turnedPro: 2012,
    memberId: 'APGC-004',
    email: 'denny.wijaya@apgc.com',
    matchPlayAvailable: true,
    isFeatured: true,
    memberDescription: 'Veteran player known for clutch performances under pressure.',
    recentResults: [
      { tournament: 'APGC Spring Championship', position: '4th', date: '2024-03-15' },
      { tournament: 'Masters Qualifier', position: '2nd', date: '2024-01-30' },
    ],
  },
  {
    name: 'Eka Putra Mahendra',
    slug: 'eka-putra-mahendra',
    rank: 5,
    country: 'Indonesia',
    gender: 'male',
    status: 'active',
    wins: 4,
    points: 1650,
    handicap: 6,
    latestGrossScore: 74,
    majorChampionships: 0,
    age: 24,
    turnedPro: 2021,
    memberId: 'APGC-005',
    email: 'eka.putra@apgc.com',
    matchPlayAvailable: true,
    isFeatured: false,
    memberDescription: 'Young talent with powerful driving distance.',
    recentResults: [
      { tournament: 'APGC Spring Championship', position: '8th', date: '2024-03-15' },
    ],
  },
  {
    name: 'Fajar Nugroho',
    slug: 'fajar-nugroho',
    rank: 6,
    country: 'Indonesia',
    gender: 'male',
    status: 'active',
    wins: 3,
    points: 1500,
    handicap: 7,
    latestGrossScore: 75,
    majorChampionships: 0,
    age: 30,
    turnedPro: 2017,
    memberId: 'APGC-006',
    email: 'fajar.nugroho@apgc.com',
    matchPlayAvailable: true,
    isFeatured: false,
    memberDescription: 'Consistent performer with excellent course management.',
    recentResults: [],
  },
  {
    name: 'Gita Purnama Sari',
    slug: 'gita-purnama-sari',
    rank: 7,
    country: 'Indonesia',
    gender: 'female',
    status: 'active',
    wins: 2,
    points: 1400,
    handicap: 8,
    latestGrossScore: 76,
    majorChampionships: 0,
    age: 23,
    turnedPro: 2022,
    memberId: 'APGC-007',
    email: 'gita.purnama@apgc.com',
    matchPlayAvailable: true,
    isFeatured: false,
    memberDescription: 'Promising young player with great potential.',
    recentResults: [],
  },
  {
    name: 'Hendra Kurniawan',
    slug: 'hendra-kurniawan',
    rank: 8,
    country: 'Indonesia',
    gender: 'male',
    status: 'active',
    wins: 2,
    points: 1350,
    handicap: 9,
    latestGrossScore: 77,
    majorChampionships: 0,
    age: 40,
    turnedPro: 2008,
    memberId: 'APGC-008',
    email: 'hendra.kurniawan@apgc.com',
    matchPlayAvailable: false,
    isFeatured: false,
    memberDescription: 'Experienced veteran and club mentor.',
    recentResults: [],
  },
]
